### ISSUE TITLE
Non-existing variable?

### ISSUE THREAD

**Issue by JanLukasGithub** [winnewoerp/my-transit-lines#12]
[Here](https://github.com/winnewoerp/my-transit-lines/blob/c6515b69887267f889cec448764f33b2c8fbf1f1/modules/mtl-proposal-form/mtl-proposal-form.php#L272) and [here](https://github.com/winnewoerp/my-transit-lines/blob/c6515b69887267f889cec448764f33b2c8fbf1f1/modules/mtl-proposal-form/mtl-proposal-form.php#L448) there are two references to a variable never defined (neither in the current version nor before I started working on this project). As both times it's used in a conditional and is negated, they should always evaluate to true and thereby be useless. Is that correct?

**Comment by winnewoerp** [comment]
Should be correct and may be a copy&paste issue from another projects that used parts of the code.
