### ISSUE TITLE
Stations appear that shouldn't exist when saving a proposal ("Haltestellenbug")

### ISSUE THREAD

**Issue by JanLukasGithub** [winnewoerp/my-transit-lines#4]
### Steps to reproduce:

1. Put a single line and x other features into a proposal
2. Save/Update the proposal
3. Edit the proposal again
4. Delete the x features
5. Change the first line by moving or adding points
6. Select the move-tool (four arrows)
7. Save the proposal

### Observed result:

When opening the proposal back up, x stations appear on the middle and then edge points of the line.

### Expected result

The features are deleted without any stations appearing out of thin air.

**Comment by JanLukasGithub** [comment]
When you edit the proposal after doing all the steps described above, the variable `mtl-count-stations` has a higher value than the actual amount of stations (which I called x in the description). Only when saving and editing again does this value decrease to x.

**Comment by JanLukasGithub** [comment]
Using the move-tool doesn't trigger any events (like `'featureunselected'` or `'featuremodified'`). I believe this to be the reason why this bug exists and also why the features don't get saved after moving them, only when doing anything else. I'm now trying to find out why this is.

**Comment by JanLukasGithub** [comment]
The solution is to unselect all features when the move-tool is selected, which fixes the bug I described above, though I cannot guarantee that there aren't other ways in which a similar bug can still be achieved. I will open a PR soon.

**Comment by winnewoerp** [comment]
Thank you, looking forward to your PR.
